from __future__ import annotations

import math
from typing import Any

from sqlmodel import Session, select

from .btf import canonicalize_btf
from .models import Bot, Track
from .security import generate_api_key, hash_api_key


def _scale_pitches(root: int, intervals: list[int], octaves: int = 2) -> list[int]:
    pitches: list[int] = []
    for o in range(octaves):
        for i in intervals:
            pitches.append(root + i + 12 * o)
    return pitches


def _mk_track(title: str, tempo: int, pitches: list[int], pattern: list[int], tpb: int = 480) -> dict[str, Any]:
    # pattern contains indices into pitches.
    events = []
    t = 0
    dur = tpb // 2  # eighth note
    for idx in pattern:
        p = pitches[idx % len(pitches)]
        v = 90
        events.append({"t": t, "dur": dur, "p": p, "v": v})
        t += dur

    return {
        "btf_version": "0.1",
        "tempo_bpm": tempo,
        "time_signature": [4, 4],
        "key": "C:maj",
        "ticks_per_beat": tpb,
        "tracks": [
            {"name": "lead", "instrument": "sine", "events": events},
        ],
    }


def _euclidean_rhythm(k: int, n: int) -> list[int]:
    # Returns a binary pattern of length n with k pulses distributed.
    if k <= 0:
        return [0] * n
    if k >= n:
        return [1] * n

    # Bjorklund algorithm (simple implementation)
    groups = [[1] for _ in range(k)] + [[0] for _ in range(n - k)]
    while True:
        start = 0
        end = len(groups) - 1
        while end > start and len(groups[start]) == len(groups[end]):
            groups[start] += groups[end]
            end -= 1
            start += 1
        groups = groups[: end + 1]
        if start == 0 or end == len(groups) - 1:
            break
    pattern = [x for g in groups for x in g]
    return pattern


def _mk_euclid_melody(title: str, tempo: int, root: int, k: int, n: int, tpb: int = 480) -> dict[str, Any]:
    # Use euclidean rhythm to decide when notes happen, and walk a scale.
    major = [0, 2, 4, 5, 7, 9, 11]
    pitches = _scale_pitches(root, major, octaves=3)
    rhythm = _euclidean_rhythm(k, n)

    events = []
    t = 0
    step = tpb // 4  # 16th
    scale_i = 0
    for hit in rhythm * 8:  # 8 bars
        if hit:
            p = pitches[scale_i % len(pitches)]
            v = 80 + (scale_i % 30)
            events.append({"t": t, "dur": step * 2, "p": p, "v": min(v, 127)})
            scale_i += 1
        t += step

    return {
        "btf_version": "0.1",
        "tempo_bpm": tempo,
        "time_signature": [4, 4],
        "key": "C:maj",
        "ticks_per_beat": tpb,
        "tracks": [
            {"name": "bells", "instrument": "triangle", "events": events},
        ],
    }


def _mk_fractal(title: str, tempo: int, root: int, tpb: int = 480) -> dict[str, Any]:
    # Recursive arpeggio-ish pattern
    major = [0, 2, 4, 5, 7, 9, 11]
    base = _scale_pitches(root, major, octaves=2)

    def motif(level: int) -> list[int]:
        if level == 0:
            return [0, 2, 4, 2]
        m = motif(level - 1)
        # expand by inserting a transposed mirror
        return m + [x + 1 for x in reversed(m)]

    pat = motif(3)
    pitches = base
    pattern = [x % len(pitches) for x in pat]
    return _mk_track(title, tempo, pitches, pattern, tpb=tpb)


def _mk_mirror_walk(title: str, tempo: int, root: int, tpb: int = 480) -> dict[str, Any]:
    minor = [0, 2, 3, 5, 7, 8, 10]
    pitches = _scale_pitches(root, minor, octaves=2)

    fwd = list(range(0, len(pitches)))
    bwd = list(reversed(fwd[1:-1]))
    walk = fwd + bwd
    pattern = walk * 2
    return _mk_track(title, tempo, pitches, pattern, tpb=tpb)


def seed_if_empty(session: Session, secret: str) -> None:
    # Create curator bot if none exists
    bot = session.exec(select(Bot).where(Bot.name == "botify-curator")).first()
    if bot is None:
        curator_key = generate_api_key()
        bot = Bot(name="botify-curator", api_key_hash=hash_api_key(curator_key, secret))
        session.add(bot)
        session.commit()

    # Seed tracks if empty
    any_track = session.exec(select(Track).limit(1)).first()
    if any_track is not None:
        return

    seeds = [
        ("Euclid Bells (5/16)", _mk_euclid_melody("Euclid Bells (5/16)", 118, 60, 5, 16)),
        ("Fractal Arp (C major)", _mk_fractal("Fractal Arp (C major)", 125, 60)),
        ("Mirror Walk (A minor)", _mk_mirror_walk("Mirror Walk (A minor)", 112, 57)),
        ("Euclid Bells (7/12)", _mk_euclid_melody("Euclid Bells (7/12)", 132, 62, 7, 12)),
    ]

    for title, btf in seeds:
        canonical_json, sha = canonicalize_btf(btf)
        track = Track(
            title=title,
            description="Seed track generated by botify-curator.",
            tags="seed,curator",
            creator_id=bot.id,
            canonical_json=canonical_json,
            sha256=sha,
        )
        session.add(track)

    session.commit()
